#!/bin/bash
# launch service in dev container

cd /workspace/sandbox_notification

( (python receiver.py) >> logs/worker1 ) &
pid[0]=$!
( (python receiver.py) >> logs/worker2 ) &
pid[1]=$!
sleep 2

trap "kill ${pid[0]}; kill ${pid[1]}; exit" INT EXIT TERM

while true
do
    echo
    echo "---"
    echo "Send notification (check /sandbox_notification/logs/ for consumer processes logs)."
    echo "Recipient name:"
    read RNAME
    echo "Recipient email:"
    read REMAIL
    echo "SMTP server:"
    read SMTPSERV
    echo "SMTP port:"
    read SMTPPORT
    echo "SMTP username:"
    read SMTPUSER
    echo "SMTP password:"
    read SMTPPASS
    echo

    bash -c "python sender.py '$RNAME' '$REMAIL' '$SMTPSERV' '$SMTPPORT' '$SMTPUSER' '$SMTPPASS'"
    sleep 3
done
