#!/bin/bash
# launch service in dev container

cd /workspace/sandbox_notification

(sandbox-notification) &
pid[0]=$!
sleep 0.1
(sandbox-notification) &
pid[1]=$!

trap "kill ${pid[0]}; kill ${pid[1]}; exit" INT EXIT TERM

cd ../tests/test_publisher

while true
do
    echo
    echo "---"
    echo "Send notification (check /sandbox_notification/logs/ for consumer processes logs)."
    echo "Recipient name:"
    read RNAME
    echo "Recipient email:"
    read REMAIL
    echo "Message:"
    read MESSAGE
    echo "Subject:"
    read SUBJECT

    python test_publisher.py "$RNAME" "$REMAIL" "$MESSAGE" "$SUBJECT"
done
